# SPDX-License-Identifier: GPL-2.0-only

dtb-$(CONFIG_ARCH_REALTEK) += rtd1293-ds418j.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-mele-v9.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-probox2-ava.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-xnano-x5.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-zidoo-x9s.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1296-ds418.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1311-pymparticles-2gb-melon.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1311-pymparticles-4gb-melon.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1312c-stormbreaker-1gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1312c-stormbreaker-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1312c-rescue.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1315c-arcreactor-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1315c-badassium-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1315c-morgan-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1315c-repulsor-1gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1315c-repulsor-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1315c-rescue.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1319-pymparticles-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1319-rescue.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1319d-steatoda-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1319d-webshooters-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1319d-rescue-nand.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1319d-rescue.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-desmodus-1gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-livingvampire-1gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-livingvampire-2gb-dmic.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-livingvampire-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-livingvampire-3gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-livingvampire-4gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-martine-1gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-martine-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-milo-1gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-milo-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-milo-3gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-milo-4gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-nikos-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-rescue-nand.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1325-rescue.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1395-bpi-m4.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1395-lionskin.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1619-mjolnir.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-backinblack-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-2gb-nand.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-3gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-4gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-rescue-nand.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-rescue.dtb
