##############################################################################
#
#    The MIT License (MIT)
#
#    Copyright (c) 2014 - 2023 Vivante Corporation
#
#    Permission is hereby granted, free of charge, to any person obtaining a
#    copy of this software and associated documentation files (the "Software"),
#    to deal in the Software without restriction, including without limitation
#    the rights to use, copy, modify, merge, publish, distribute, sublicense,
#    and/or sell copies of the Software, and to permit persons to whom the
#    Software is furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in
#    all copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#    DEALINGS IN THE SOFTWARE.
#
##############################################################################


#
# Linux build file for architecture dependent kernel HAL layer.
#

################################################################################
# Include common definitions.

include $(AQROOT)/makefile.linux.def

################################################################################
# Define a shortcut for the main target.

STATIC = 1
TARGET_NAME = libhalarchkernel.a

################################################################################
# Supply additional include directories.

INCLUDE += -I$(AQROOT)/hal/kernel/inc
INCLUDE += -I$(AQROOT)/hal/kernel/inc
INCLUDE += -I$(AQROOT)/hal/kernel
INCLUDE += -I$(AQROOT)/hal/kernel/arch

ifeq ($(LINUX_EMULATOR),1)
CFLAGS += $(INCLUDE) -Werror -fPIC
else
CFLAGS += $(INCLUDE) -Werror -ansi
endif


################################################################################
# Describe object files.

OBJECTS = $(OBJ_DIR)/gc_hal_kernel_context.o \
          $(OBJ_DIR)/gc_hal_kernel_hardware.o \
          $(OBJ_DIR)/gc_hal_kernel_hardware_func.o \
          $(OBJ_DIR)/gc_hal_kernel_hardware_func_flop_reset.o \
          $(OBJ_DIR)/gc_hal_kernel_hardware_async_fe.o \
          $(OBJ_DIR)/gc_hal_kernel_hardware_mc_fe.o \
          $(OBJ_DIR)/gc_hal_kernel_hardware_waitlink_fe.o

include $(AQROOT)/common.target
